namespace SqlWhiteboard.Lexical

type ODBCKeyword = 
  | ABSOLUTE
  | ACTION
  | ADA
  | ADD
  | ALL
  | ALLOCATE
  | ALTER
  | AND
  | ANY
  | ARE
  | AS
  | ASC
  | ASSERTION
  | AT
  | AUTHORIZATION
  | AVG
  | BEGIN
  | BETWEEN
  | BIT
  | BIT_LENGTH
  | BOTH
  | BY
  | CASCADE
  | CASCADED
  | CASE
  | CAST
  | CATALOG
  | CHAR
  | CHARACTER
  | CHARACTER_LENGTH
  | CHAR_LENGTH
  | CHECK
  | CLOSE
  | COALESCE
  | COLLATE
  | COLLATION
  | COLUMN
  | COMMIT
  | CONNECT
  | CONNECTION
  | CONSTRAINT
  | CONSTRAINTS
  | CONTINUE
  | CONVERT
  | CORRESPONDING
  | COUNT
  | CREATE
  | CROSS
  | CURRENT
  | CURRENT_DATE
  | CURRENT_TIME
  | CURRENT_TIMESTAMP
  | CURRENT_USER
  | CURSOR
  | DATE
  | DAY
  | DEALLOCATE
  | DEC
  | DECIMAL
  | DECLARE
  | DEFAULT
  | DEFERRABLE
  | DEFERRED
  | DELETE
  | DESC
  | DESCRIBE
  | DESCRIPTOR
  | DIAGNOSTICS
  | DISCONNECT
  | DISTINCT
  | DOMAIN
  | DOUBLE
  | DROP
  | ELSE
  | END
  | ``END-EXEC``
  | ESCAPE
  | EXCEPT
  | EXCEPTION
  | EXEC
  | EXECUTE
  | EXISTS
  | EXTERNAL
  | EXTRACT
  | FALSE
  | FETCH
  | FIRST
  | FLOAT
  | FOR
  | FOREIGN
  | FORTRAN
  | FOUND
  | FROM
  | FULL
  | GET
  | GLOBAL
  | GO
  | GOTO
  | GRANT
  | GROUP
  | HAVING
  | HOUR
  | IDENTITY
  | IMMEDIATE
  | IN
  | INCLUDE
  | INDEX
  | INDICATOR
  | INITIALLY
  | INNER
  | INPUT
  | INSENSITIVE
  | INSERT
  | INT
  | INTEGER
  | INTERSECT
  | INTERVAL
  | INTO
  | IS
  | ISOLATION
  | JOIN
  | KEY
  | LANGUAGE
  | LAST
  | LEADING
  | LEFT
  | LEVEL
  | LIKE
  | LOCAL
  | LOWER
  | MATCH
  | MAX
  | MIN
  | MINUTE
  | MODULE
  | MONTH
  | NAMES
  | NATIONAL
  | NATURAL
  | NCHAR
  | NEXT
  | NO
  | NONE
  | NOT
  | NULL
  | NULLIF
  | NUMERIC
  | OCTET_LENGTH
  | OF
  | ON
  | ONLY
  | OPEN
  | OPTION
  | OR
  | ORDER
  | OUTER
  | OUTPUT
  | OVERLAPS
  | PAD
  | PARTIAL
  | PASCAL
  | POSITION
  | PRECISION
  | PREPARE
  | PRESERVE
  | PRIMARY
  | PRIOR
  | PRIVILEGES
  | PROCEDURE
  | PUBLIC
  | READ
  | REAL
  | REFERENCES
  | RELATIVE
  | RESTRICT
  | REVOKE
  | RIGHT
  | ROLLBACK
  | ROWS
  | SCHEMA
  | SCROLL
  | SECOND
  | SECTION
  | SELECT
  | SESSION
  | SESSION_USER
  | SET
  | SIZE
  | SMALLINT
  | SOME
  | SPACE
  | SQL
  | SQLCA
  | SQLCODE
  | SQLERROR
  | SQLSTATE
  | SQLWARNING
  | SUBSTRING
  | SUM
  | SYSTEM_USER
  | TABLE
  | TEMPORARY
  | THEN
  | TIME
  | TIMESTAMP
  | TIMEZONE_HOUR
  | TIMEZONE_MINUTE
  | TO
  | TRAILING
  | TRANSACTION
  | TRANSLATE
  | TRANSLATION
  | TRIM
  | TRUE
  | UNION
  | UNIQUE
  | UNKNOWN
  | UPDATE
  | UPPER
  | USAGE
  | USER
  | USING
  | VALUE
  | VALUES
  | VARCHAR
  | VARYING
  | VIEW
  | WHEN
  | WHENEVER
  | WHERE
  | WITH
  | WORK
  | WRITE
  | YEAR
  | ZONE

module ODBCKeywordModule = 
  ///Use for unit tests ONLY
  let GetODBCKeywordCases() = SqlWhiteboard.Core.Reflection.GetUnionCases<ODBCKeyword>()
  
  let ODBCKeywordLookup = 
    [| "ABSOLUTE", ABSOLUTE
       "ACTION", ACTION
       "ADA", ADA
       "ADD", ADD
       "ALL", ALL
       "ALLOCATE", ALLOCATE
       "ALTER", ALTER
       "AND", AND
       "ANY", ANY
       "ARE", ARE
       "AS", AS
       "ASC", ASC
       "ASSERTION", ASSERTION
       "AT", AT
       "AUTHORIZATION", AUTHORIZATION
       "AVG", AVG
       "BEGIN", BEGIN
       "BETWEEN", BETWEEN
       "BIT", BIT
       "BIT_LENGTH", BIT_LENGTH
       "BOTH", BOTH
       "BY", BY
       "CASCADE", CASCADE
       "CASCADED", CASCADED
       "CASE", CASE
       "CAST", CAST
       "CATALOG", CATALOG
       "CHAR", CHAR
       "CHARACTER", CHARACTER
       "CHARACTER_LENGTH", CHARACTER_LENGTH
       "CHAR_LENGTH", CHAR_LENGTH
       "CHECK", CHECK
       "CLOSE", CLOSE
       "COALESCE", COALESCE
       "COLLATE", COLLATE
       "COLLATION", COLLATION
       "COLUMN", COLUMN
       "COMMIT", COMMIT
       "CONNECT", CONNECT
       "CONNECTION", CONNECTION
       "CONSTRAINT", CONSTRAINT
       "CONSTRAINTS", CONSTRAINTS
       "CONTINUE", CONTINUE
       "CONVERT", CONVERT
       "CORRESPONDING", CORRESPONDING
       "COUNT", COUNT
       "CREATE", CREATE
       "CROSS", CROSS
       "CURRENT", CURRENT
       "CURRENT_DATE", CURRENT_DATE
       "CURRENT_TIME", CURRENT_TIME
       "CURRENT_TIMESTAMP", CURRENT_TIMESTAMP
       "CURRENT_USER", CURRENT_USER
       "CURSOR", CURSOR
       "DATE", DATE
       "DAY", DAY
       "DEALLOCATE", DEALLOCATE
       "DEC", DEC
       "DECIMAL", DECIMAL
       "DECLARE", DECLARE
       "DEFAULT", DEFAULT
       "DEFERRABLE", DEFERRABLE
       "DEFERRED", DEFERRED
       "DELETE", DELETE
       "DESC", DESC
       "DESCRIBE", DESCRIBE
       "DESCRIPTOR", DESCRIPTOR
       "DIAGNOSTICS", DIAGNOSTICS
       "DISCONNECT", DISCONNECT
       "DISTINCT", DISTINCT
       "DOMAIN", DOMAIN
       "DOUBLE", DOUBLE
       "DROP", DROP
       "ELSE", ELSE
       "END", END
       "END-EXEC", ``END-EXEC``
       "ESCAPE", ESCAPE
       "EXCEPT", EXCEPT
       "EXCEPTION", EXCEPTION
       "EXEC", EXEC
       "EXECUTE", EXECUTE
       "EXISTS", EXISTS
       "EXTERNAL", EXTERNAL
       "EXTRACT", EXTRACT
       "FALSE", FALSE
       "FETCH", FETCH
       "FIRST", FIRST
       "FLOAT", FLOAT
       "FOR", FOR
       "FOREIGN", FOREIGN
       "FORTRAN", FORTRAN
       "FOUND", FOUND
       "FROM", FROM
       "FULL", FULL
       "GET", GET
       "GLOBAL", GLOBAL
       "GO", GO
       "GOTO", GOTO
       "GRANT", GRANT
       "GROUP", GROUP
       "HAVING", HAVING
       "HOUR", HOUR
       "IDENTITY", IDENTITY
       "IMMEDIATE", IMMEDIATE
       "IN", IN
       "INCLUDE", INCLUDE
       "INDEX", INDEX
       "INDICATOR", INDICATOR
       "INITIALLY", INITIALLY
       "INNER", INNER
       "INPUT", INPUT
       "INSENSITIVE", INSENSITIVE
       "INSERT", INSERT
       "INT", INT
       "INTEGER", INTEGER
       "INTERSECT", INTERSECT
       "INTERVAL", INTERVAL
       "INTO", INTO
       "IS", IS
       "ISOLATION", ISOLATION
       "JOIN", JOIN
       "KEY", KEY
       "LANGUAGE", LANGUAGE
       "LAST", LAST
       "LEADING", LEADING
       "LEFT", LEFT
       "LEVEL", LEVEL
       "LIKE", LIKE
       "LOCAL", LOCAL
       "LOWER", LOWER
       "MATCH", MATCH
       "MAX", MAX
       "MIN", MIN
       "MINUTE", MINUTE
       "MODULE", MODULE
       "MONTH", MONTH
       "NAMES", NAMES
       "NATIONAL", NATIONAL
       "NATURAL", NATURAL
       "NCHAR", NCHAR
       "NEXT", NEXT
       "NO", NO
       "NONE", NONE
       "NOT", NOT
       "NULL", NULL
       "NULLIF", NULLIF
       "NUMERIC", NUMERIC
       "OCTET_LENGTH", OCTET_LENGTH
       "OF", OF
       "ON", ON
       "ONLY", ONLY
       "OPEN", OPEN
       "OPTION", OPTION
       "OR", OR
       "ORDER", ORDER
       "OUTER", OUTER
       "OUTPUT", OUTPUT
       "OVERLAPS", OVERLAPS
       "PAD", PAD
       "PARTIAL", PARTIAL
       "PASCAL", PASCAL
       "POSITION", POSITION
       "PRECISION", PRECISION
       "PREPARE", PREPARE
       "PRESERVE", PRESERVE
       "PRIMARY", PRIMARY
       "PRIOR", PRIOR
       "PRIVILEGES", PRIVILEGES
       "PROCEDURE", PROCEDURE
       "PUBLIC", PUBLIC
       "READ", READ
       "REAL", REAL
       "REFERENCES", REFERENCES
       "RELATIVE", RELATIVE
       "RESTRICT", RESTRICT
       "REVOKE", REVOKE
       "RIGHT", RIGHT
       "ROLLBACK", ROLLBACK
       "ROWS", ROWS
       "SCHEMA", SCHEMA
       "SCROLL", SCROLL
       "SECOND", SECOND
       "SECTION", SECTION
       "SELECT", SELECT
       "SESSION", SESSION
       "SESSION_USER", SESSION_USER
       "SET", SET
       "SIZE", SIZE
       "SMALLINT", SMALLINT
       "SOME", SOME
       "SPACE", SPACE
       "SQL", SQL
       "SQLCA", SQLCA
       "SQLCODE", SQLCODE
       "SQLERROR", SQLERROR
       "SQLSTATE", SQLSTATE
       "SQLWARNING", SQLWARNING
       "SUBSTRING", SUBSTRING
       "SUM", SUM
       "SYSTEM_USER", SYSTEM_USER
       "TABLE", TABLE
       "TEMPORARY", TEMPORARY
       "THEN", THEN
       "TIME", TIME
       "TIMESTAMP", TIMESTAMP
       "TIMEZONE_HOUR", TIMEZONE_HOUR
       "TIMEZONE_MINUTE", TIMEZONE_MINUTE
       "TO", TO
       "TRAILING", TRAILING
       "TRANSACTION", TRANSACTION
       "TRANSLATE", TRANSLATE
       "TRANSLATION", TRANSLATION
       "TRIM", TRIM
       "TRUE", TRUE
       "UNION", UNION
       "UNIQUE", UNIQUE
       "UNKNOWN", UNKNOWN
       "UPDATE", UPDATE
       "UPPER", UPPER
       "USAGE", USAGE
       "USER", USER
       "USING", USING
       "VALUE", VALUE
       "VALUES", VALUES
       "VARCHAR", VARCHAR
       "VARYING", VARYING
       "VIEW", VIEW
       "WHEN", WHEN
       "WHENEVER", WHENEVER
       "WHERE", WHERE
       "WITH", WITH
       "WORK", WORK
       "WRITE", WRITE
       "YEAR", YEAR
       "ZONE", ZONE |]
    |> dict
  
  ///Gets the appropriate Union Case from mapping, if any.
  let ParseODBCKeyword(words : string) = 
    match ODBCKeywordLookup.TryGetValue(words.ToUpper()) with
    | true, result -> Some(result)
    | _ -> None
